<template>
  <div class="maintenance">
    <h2 class="section-title">Maintenance</h2>
    <p class="panel-sub">
      Clear one kind of artifact without re-ingesting everything — for swapping an
      embedding or summarisation backend. Your own tags and reading lists are never
      touched.
    </p>

    <div class="table-wrap">
      <table v-if="rows.length" class="tag-table">
        <thead>
          <tr>
            <th>Target</th>
            <th class="right">Stored</th>
            <th>Regenerated by</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.key">
            <td>
              <div class="target-label">{{ row.label }}</div>
              <div class="hint">{{ TIER_LABELS[row.tier] ?? `tier ${row.tier}` }}</div>
            </td>
            <td class="right nowrap">{{ countLabel(row) }}</td>
            <td class="retrigger-cell">
              <button
                v-if="retriggerFor(row.key)"
                class="btn-xs btn-xs--ok"
                :disabled="busy !== null"
                @click="retrigger(row)"
              >
                {{ retriggerFor(row.key)!.label }}
              </button>
              <span v-else class="hint">{{ row.retrigger ?? '—' }}</span>
            </td>
            <td class="right">
              <button
                class="btn-xs btn-xs--danger"
                :disabled="busy !== null || isEmpty(row) || jobRunning"
                :title="purgeTitle(row)"
                @click="purge(row)"
              >
                {{ busy === row.key ? 'Purging…' : 'Purge' }}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
      <p v-else class="empty-hint">
        {{ loading ? 'Loading targets…' : 'No purge targets available.' }}
      </p>
    </div>

    <p v-if="jobRunning" class="hint running-hint">
      A sync is running — purging is disabled until it finishes.
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import * as api from '@/api/client'
import type { PurgeTargetRow } from '@/api/client'
import { notifyError } from '@/lib/notifyError'
import { useIngestionStore } from '@/stores/ingestion'
import { useToastStore } from '@/stores/toast'

const ingest = useIngestionStore()
const toast = useToastStore()

const rows = ref<PurgeTargetRow[]>([])
const loading = ref(true)
const busy = ref<string | null>(null)

const TIER_LABELS: Record<number, string> = {
  2: 'model output — costs inference to rebuild',
  3: 'source data — costs a re-read or re-fetch',
}

/**
 * Re-triggers the panel can run itself. The backend's `retrigger` string names
 * what regenerates each target, but only these two are self-contained enough to
 * fire from here — the rest kick off a full source sync (thousands of outbound
 * fetches, for the fetch targets) and belong on the page that shows progress,
 * so those render as a hint instead of a button.
 */
const RETRIGGERS: Record<string, { label: string; run: () => Promise<unknown>; note: string }> = {
  summaries: {
    label: 'Re-summarise',
    run: () => api.enrich('summary'),
    note: 'Summarising documents that have none. Runs in the background.',
  },
  vectors: {
    label: 'Rebuild',
    run: () => api.rebuildVectors(),
    note: 'Re-embedding every chunk. Runs in the background.',
  },
}

const jobRunning = computed(() => ingest.isAnyJobRunning())

function retriggerFor(key: string) {
  return RETRIGGERS[key] ?? null
}

/** Rows report per-table counts; the total is what "is there anything here" means. */
function total(row: PurgeTargetRow): number {
  return Object.values(row.counts).reduce((a, b) => a + b, 0)
}

function isEmpty(row: PurgeTargetRow): boolean {
  return total(row) === 0
}

function countLabel(row: PurgeTargetRow): string {
  const parts = Object.entries(row.counts)
    .filter(([, n]) => n > 0)
    .map(([name, n]) => `${n.toLocaleString()} ${name.replace(/_/g, ' ')}`)
  return parts.length ? parts.join(' · ') : '—'
}

function purgeTitle(row: PurgeTargetRow): string {
  if (jobRunning.value) return 'A sync is running'
  if (isEmpty(row)) return 'Nothing stored for this target'
  return `Delete ${countLabel(row)}`
}

async function load() {
  loading.value = true
  try {
    rows.value = (await api.purgeTargets()).targets
  } catch (e) {
    notifyError(e)
  } finally {
    loading.value = false
  }
}

async function purge(row: PurgeTargetRow) {
  if (busy.value) return
  busy.value = row.key
  try {
    // Re-count at click time rather than trusting the rendered row: the confirm
    // dialog is a promise about what this button is about to delete.
    const preview = await api.purgeTarget(row.key, { dryRun: true })
    const summary = countLabel({ ...row, counts: preview.counts })
    if (summary === '—') {
      toast.push(`${row.label}: nothing to purge`, 'info')
      await load()
      return
    }
    const regen = row.retrigger ? `\n\nRegenerate with: ${row.retrigger}` : ''
    if (!window.confirm(`Permanently delete ${summary}?\n\nThis cannot be undone.${regen}`)) return

    const res = await api.purgeTarget(row.key)
    toast.push(`${row.label}: purged ${countLabel({ ...row, counts: res.counts })}`, 'info')
    await Promise.all([load(), ingest.load(true)])
  } catch (e) {
    notifyError(e)
  } finally {
    busy.value = null
  }
}

async function retrigger(row: PurgeTargetRow) {
  const action = retriggerFor(row.key)
  if (!action || busy.value) return
  busy.value = row.key
  try {
    await action.run()
    toast.push(`${row.label}: ${action.note}`, 'info')
  } catch (e) {
    notifyError(e)
  } finally {
    busy.value = null
  }
}

onMounted(load)
</script>

<style scoped>
.maintenance { margin-top: 24px }
.panel-sub { font-size: 12px; color: var(--muted); margin: -4px 0 10px }
.target-label { font-size: 13px }
.nowrap { white-space: nowrap }
.retrigger-cell { font-size: 12px }
.empty-hint { padding: 14px 12px; font-size: 12px; color: var(--hint) }
.running-hint { margin-top: 8px }
</style>
