import type { components } from './types.gen'

// Typed API client — one function per endpoint.
// All paths are relative so the Vite proxy routes them to FastAPI in dev,
// and FastAPI serves them directly from /dist in production.

const BASE = ''
const DEFAULT_TIMEOUT_MS = 30000
const INGESTION_TIMEOUT_MS = 120000
/** One Ollama call per doc; default batch 20 × ~60s + slack (must exceed DEFAULT_TIMEOUT_MS). */
const PSEUDO_LABEL_LLM_PER_DOC_MS = 65_000
const PSEUDO_LABEL_LLM_BASE_MS = 15_000
const PSEUDO_LABEL_LLM_MAX_MS = 30 * 60 * 1000

function pseudoLabelLlmTimeoutMs(batchSize?: number): number {
  const n = batchSize ?? 20
  return Math.min(
    PSEUDO_LABEL_LLM_MAX_MS,
    PSEUDO_LABEL_LLM_BASE_MS + n * PSEUDO_LABEL_LLM_PER_DOC_MS,
  )
}

export class ApiError extends Error {
  status: number
  constructor(msg: string, status: number) {
    super(msg)
    this.status = status
    this.name = 'ApiError'
  }
}

async function req<T>(
  path: string,
  options: RequestInit = {},
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<T> {
  const ctrl = new AbortController()
  const timer = timeoutMs > 0
    ? setTimeout(() => ctrl.abort(), timeoutMs)
    : null
  try {
    const r = await fetch(BASE + path, {
      headers: { 'Content-Type': 'application/json' },
      signal: ctrl.signal,
      ...options,
    })
    if (!r.ok) {
      let detail = r.statusText
      try { detail = (await r.json()).detail ?? detail } catch { /* keep statusText */ }
      throw new ApiError(`${r.status} ${detail} — ${path}`, r.status)
    }
    if (r.status === 204) return undefined as T
    return r.json()
  } catch (e: unknown) {
    // An aborted fetch rejects with a DOMException, which subclasses Error.
    if (e instanceof Error && e.name === 'AbortError') {
      throw new ApiError(`Timeout: ${path}`, 0)
    }
    throw e
  } finally {
    if (timer) clearTimeout(timer)
  }
}

// ── Types ─────────────────────────────────────────────────────────────────────
//
// Everything the backend declares a `response_model` for is aliased from
// `types.gen.ts`, generated by `npm run gen:api` from `openapi.json`, which
// `python scripts/dump_openapi.py` writes from the live FastAPI app. These names
// used to be hand-written twins of the pydantic models, edited twice per schema
// change with nothing checking they still agreed;
// `tests/test_openapi_snapshot.py` now fails when the app drifts from the
// snapshot. The exported names are unchanged, so callers import exactly what
// they did before.
type Schemas = components['schemas']

export type ApplyAllTagsResult = Schemas['ApplyAllTagsResult']
export type ApplyTagResult = Schemas['ApplyTagResult']
export type CapabilityStatus = Schemas['CapabilityStatus']
export type ClusterDetail = Schemas['ClusterDetail']
export type ClusterOut = Schemas['ClusterOut']
export type ClusterPatchRequest = Schemas['ClusterPatchRequest']
// The backend types `drift_flags` and `merge_suggestions` as `list[dict]`, so the
// generated element type is a bare index signature. The element shapes below are
// only known here; give those fields real models server-side and these overrides
// can go.
export type DiagnosticsOut = Omit<
  Schemas['DiagnosticsOut'], 'drift_flags' | 'merge_suggestions'
> & {
  drift_flags: DriftFlag[]
  merge_suggestions: MergeSuggestion[]
}
export type DocumentDetail = Schemas['DocumentDetail']
export type TagAlias = Schemas['TagAliasOut']
export type DuplicateLink = Schemas['DuplicateLinkOut']
export type DuplicateScanResult = Schemas['DuplicateScanResult']
export type TagAliasScanResult = Schemas['ScanResult']
export type TagVariantGroup = Schemas['VariantGroup']
export type DocumentListItem = Schemas['DocumentListItem']
export type DocumentListResponse = Schemas['DocumentListResponse']
export type DocumentOut = Schemas['DocumentOut']
export type DomainRow = Schemas['DomainRow']
export type DomainTopLists = Schemas['DomainTopLists']
export type ImageDetail = Schemas['ImageDetail']
export type ImageOut = Schemas['ImageOut']
export type ProbeResult = Schemas['ProbeResult']
export type RedditDetail = Schemas['RedditDetail']
export type RunOut = Schemas['RunOut']
// A request body, not a response: openapi-typescript marks a property with a
// default as required because a *response* always carries it, but the caller may
// omit any of these and let the server apply its default. Only `query` is in the
// schema's `required` list.
export type SearchRequest =
  Partial<Schemas['SearchRequest']> & Pick<Schemas['SearchRequest'], 'query'>
export type SearchResponse = Schemas['SearchResponse']
export type SettingField = Schemas['SettingField']
export type SettingGroup = Schemas['SettingGroup']
export type SettingsReport = Schemas['SettingsReport']
export type TagOut = Schemas['TagOut']
export type UmapPoint = Schemas['UmapPoint']

// Hand-written still: these endpoints return a plain dict rather than a
// declared `response_model`, so the schema has nothing to generate from. Give a
// route a response_model and its shape moves into the generated block above.

export type RedditKind = 'post' | 'comment'
/** Reddit-only fields for a saved post or comment. Null for every other source. */
export type EnrichmentKind     = 'summary' | 'external_synopsis'
export type EnrichmentResolver = 'isbn' | 'search' | 'google_books' | 'brave' | 'local_model'
/** One rung of the enrichment cascade that produced generated text (DESIGN.md §3.2). */
export interface Enrichment {
  kind: EnrichmentKind
  /** Null when the backend could not name the rung. */
  resolved_by: EnrichmentResolver | null
  /** Human-readable, already localised by the backend — render as-is. */
  label: string
  source_ref: string | null
  ref_title: string | null
  text: string
}
export interface ClusterRunParams {
  cluster_space?: 'pca' | 'legacy_umap' | 'agglomerative' | null
  min_cluster_size?: number | null
  min_samples?: number | null
  n_neighbors?: number | null
  min_dist?: number
  pca_components?: number | null
  n_components?: number
  linkage?: 'ward' | 'average' | 'complete' | 'single' | null
  n_clusters?: number | null
  distance_threshold?: number | null
  skip_labelling?: boolean
  async_labelling?: boolean
}
export interface DriftFlag     { cluster_id: number; label: string; drift_score: number; n_recent: number; flagged: boolean }
export interface MergeSuggestion { cluster_id_a: number; label_a: string; cluster_id_b: number; label_b: string; similarity: number }
// `variants`: the stored spellings folded into this row (DESIGN.md §3.8).
export interface TagRow        { tag: string; origin: string; count: number; variants?: string[] }
export interface IngestionStatus {
  total: number
  by_source: Record<string, number>
  pending_metadata_by_source?: Record<string, number>
  fetch_by_source?: Record<string, Record<string, number>>
  source_unavailable?: Record<string, string | null>
  unfetchable: number
  pending: number
}
export interface PhaseBreakdown {
  success: number
  failure: number
  pending: number
}
export interface PhaseDetail {
  name: string
  total: number
  processed: number
  percent: number
  active: boolean
  breakdown?: PhaseBreakdown
}
export interface SyncProgress {
  source: string
  status: 'idle' | 'running' | 'done' | 'error' | 'paused' | 'cancelled'
  phase: string
  active_job: 'metadata' | 'ingest' | null
  total: number
  processed: number
  failed: number
  percent: number
  overall_total: number
  overall_processed: number
  phase_index: number
  phase_count: number
  phases: string[]
  phase_details: PhaseDetail[]
  error: string | null
  last_result?: Record<string, unknown> | null
}
export interface SourceCounts {
  pending_metadata: number
  fetch: Record<string, number>
  unavailable: string | null
}
/** One frame of ``GET /ingestion/sync/events``. */
export interface SyncEvent {
  progress: SyncProgress
  counts: SourceCounts
}
export interface UnfetchableRow  { id: number; title: string; url: string; http_status: number | null; error: string | null; timestamp: number }
export interface ReadingList   { list_id: number; name: string; description: string; created_at: number; item_count: number }
export interface ReadingListItem { id: number; position: number; note: string; doc_id: number; title: string; source: string; url_or_path: string | null }

// ── Search ────────────────────────────────────────────────────────────────────

export const search = (body: SearchRequest) =>
  req<SearchResponse>('/search', { method: 'POST', body: JSON.stringify(body) })

// ── Documents ─────────────────────────────────────────────────────────────────

export const getDocument = async (id: number): Promise<DocumentDetail> => {
  const doc = await req<DocumentDetail>(`/documents/${id}`)
  // Older backends omit `enrichment`; keep it an array so callers can iterate freely.
  return Array.isArray(doc.enrichment) ? doc : { ...doc, enrichment: [] }
}

export const listDocuments = (params?: {
  sources?: string[]
  source_tags?: string[]
  general_tags?: string[]
  overlay_tags?: string[]
  cluster_l1_tags?: string[]
  cluster_l2_tags?: string[]
  learned_tags?: string[]
  collection_tags?: string[]
  wayback_only?: boolean
  limit?: number
  offset?: number
}) => {
  const qs = new URLSearchParams()
  params?.sources?.forEach(s => qs.append('sources', s))
  params?.source_tags?.forEach(t => qs.append('source_tags', t))
  params?.general_tags?.forEach(t => qs.append('general_tags', t))
  params?.overlay_tags?.forEach(t => qs.append('overlay_tags', t))
  params?.cluster_l1_tags?.forEach(t => qs.append('cluster_l1_tags', t))
  params?.cluster_l2_tags?.forEach(t => qs.append('cluster_l2_tags', t))
  params?.learned_tags?.forEach(t => qs.append('learned_tags', t))
  params?.collection_tags?.forEach(t => qs.append('collection_tags', t))
  if (params?.wayback_only) qs.set('wayback_only', 'true')
  if (params?.limit != null) qs.set('limit', String(params.limit))
  if (params?.offset != null) qs.set('offset', String(params.offset))
  const query = qs.toString()
  return req<DocumentListResponse>(`/documents${query ? '?' + query : ''}`)
}

export const patchTags = (id: number, add: string[], remove: string[]) =>
  req<void>(`/documents/${id}/tags`, { method: 'PATCH', body: JSON.stringify({ add, remove }) })

// ── Clusters ──────────────────────────────────────────────────────────────────

export const listClusters    = ()  => req<ClusterOut[]>('/clusters')
export const getCluster      = (id: number) => req<ClusterDetail>(`/clusters/${id}`)
export const clusterDocs     = (id: number, limit = 20, offset = 0) =>
  req<DocumentOut[]>(`/clusters/${id}/documents?limit=${limit}&offset=${offset}`)
export const scatterPoints   = ()  => req<UmapPoint[]>('/clusters/scatter/points')
export const applyClusterTag = (id: number, tag?: string) =>
  req<ApplyTagResult>(`/clusters/${id}/apply-tag`, {
    method: 'POST',
    body: JSON.stringify(tag ? { tag } : {}),
  })
export const patchCluster = (id: number, body: ClusterPatchRequest) =>
  req<ClusterOut>(`/clusters/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const regenerateClusterLabel = (id: number) =>
  req<ClusterOut>(`/clusters/${id}/regenerate-label`, { method: 'POST', body: '{}' })
export const applyAllClusterTags = () =>
  req<ApplyAllTagsResult>('/clusters/apply-all-tags', { method: 'POST', body: '{}' })

// ── Runs ──────────────────────────────────────────────────────────────────────

export const listRuns        = ()  => req<RunOut[]>('/runs')
export const getDiagnostics  = (id: number) => req<DiagnosticsOut>(`/runs/${id}/diagnostics`)
export const acceptRun       = (id: number) => req<void>(`/runs/${id}/accept`, { method: 'POST' })
export const rejectRun       = (id: number, notes = '') =>
  req<void>(`/runs/${id}/reject?notes=${encodeURIComponent(notes)}`, { method: 'POST' })
export const triggerRun      = (params?: ClusterRunParams) =>
  req<{ status: string; run_id: number }>('/runs/trigger', { method: 'POST', body: JSON.stringify(params ?? {}) })
export const cancelRun       = (id: number) =>
  req<{ status: string; run_id: number }>(`/runs/${id}/cancel`, { method: 'POST' })
export const deleteRun       = (id: number, force = false) =>
  req<void>(`/runs/${id}${force ? '?force=true' : ''}`, { method: 'DELETE' })

// ── Tags ──────────────────────────────────────────────────────────────────────

export const listTags = (params?: {
  origin?: string
  sources?: string[]
  source_tags?: string[]
  cluster_l1_tags?: string[]
  cluster_l2_tags?: string[]
  collection_tags?: string[]
  wayback_only?: boolean
  q?: string
  limit?: number
}) => {
  const qs = new URLSearchParams()
  if (params?.origin) qs.set('origin', params.origin)
  params?.sources?.forEach(s => qs.append('sources', s))
  params?.source_tags?.forEach(t => qs.append('source_tags', t))
  params?.cluster_l1_tags?.forEach(t => qs.append('cluster_l1_tags', t))
  params?.cluster_l2_tags?.forEach(t => qs.append('cluster_l2_tags', t))
  params?.collection_tags?.forEach(t => qs.append('collection_tags', t))
  if (params?.wayback_only) qs.set('wayback_only', 'true')
  if (params?.q) qs.set('q', params.q)
  if (params?.limit != null) qs.set('limit', String(params.limit))
  const query = qs.toString()
  return req<TagRow[]>(`/tags${query ? '?' + query : ''}`)
}

// ── Trends ────────────────────────────────────────────────────────────────────

export interface TrendTimelineResponse {
  timeline: Record<string, Record<string, number>>
  sizes: Record<string, number>
}

export const trendTimeline = () =>
  req<TrendTimelineResponse>('/trends/timeline')
export const trendSources  = (granularity: 'month' | 'year' = 'month') =>
  req<Record<string, Record<string, number>>>(`/trends/sources?granularity=${granularity}`)

// ── Ingestion ─────────────────────────────────────────────────────────────────

export const ingestionStatus    = () =>
  req<IngestionStatus>('/ingestion/status', {}, INGESTION_TIMEOUT_MS)
export const syncProgress       = (source?: string) =>
  req<Record<string, SyncProgress>>(
    `/ingestion/sync/progress${source ? `?source=${source}` : ''}`,
    {},
    0,
  )
/**
 * Live progress for one source over SSE. The server closes the stream once the
 * job reaches a terminal state, so ``onEvent`` sees that last frame and the
 * caller closes the source to stop EventSource from reconnecting.
 */
export function syncEvents(
  source: string,
  onEvent: (ev: SyncEvent) => void,
  onError?: () => void,
): EventSource {
  const es = new EventSource(`${BASE}/ingestion/sync/events?source=${encodeURIComponent(source)}`)
  es.onmessage = (msg) => {
    try { onEvent(JSON.parse(msg.data) as SyncEvent) } catch { /* ignore malformed frame */ }
  }
  es.onerror = () => { onError?.() }
  return es
}
export const unfetchableUrls    = (limit = 50, offset = 0) =>
  req<UnfetchableRow[]>(
    `/ingestion/unfetchable?limit=${limit}&offset=${offset}`,
    {},
    INGESTION_TIMEOUT_MS,
  )
export const domainTopLists     = (limit = 10, source?: string) =>
  req<DomainTopLists>(
    `/ingestion/domains?limit=${limit}${source ? `&source=${encodeURIComponent(source)}` : ''}`,
    {},
    INGESTION_TIMEOUT_MS,
  )
export const syncSource         = (source: string, force = false) =>
  req<{ status: string; source: string }>(
    `/ingestion/sync/${source}${force ? '?force=1' : ''}`,
    { method: 'POST' },
    10000,
  )
/** Re-walk a source's whole remote history rather than only what is new.
 *  Only sources in the backend's BACKFILL_SOURCES accept this (reddit today);
 *  anything else answers 400. */
export const backfillMetadata   = (source: string, force = false) =>
  req<{ status: string; backfill: boolean }>(
    `/ingestion/sync/${source}/metadata?backfill=1${force ? '&force=1' : ''}`,
    { method: 'POST' },
  )
export const syncMetadata       = (source: string, force = false) =>
  req<{ status: string; source: string; job: string }>(
    `/ingestion/sync/${source}/metadata${force ? '?force=1' : ''}`,
    { method: 'POST' },
    10000,
  )
export const syncIngest         = (source: string, force = false) =>
  req<{ status: string; source: string; job: string }>(
    `/ingestion/sync/${source}/ingest${force ? '?force=1' : ''}`,
    { method: 'POST' },
    10000,
  )
export const pauseSync          = (source: string) =>
  req<{ status: string; source: string }>(
    `/ingestion/sync/${source}/pause`,
    { method: 'POST' },
    10000,
  )
export const cancelSync         = (source: string) =>
  req<{ status: string; source: string }>(
    `/ingestion/sync/${source}/cancel`,
    { method: 'POST' },
    10000,
  )

export interface PurgeResult { status: string; source: string; counts: Record<string, number> }
export const purgeSource        = (source: string) =>
  req<PurgeResult>(
    `/ingestion/sources/${source}/purge`,
    { method: 'POST' },
    INGESTION_TIMEOUT_MS,
  )

// ── Maintenance: selective purge and enrichment re-triggers ───────────────────
// One row per registered target in pka/purge.py; `counts` is the dry run, so a
// button can say what it will delete before it is pressed.

export interface PurgeTargetRow {
  key: string
  label: string
  /** 2 = model-derived (re-runnable at a cost in inference), 3 = source-derived. */
  tier: number
  /** Endpoint or command that regenerates it, for display; null if nothing does. */
  retrigger: string | null
  counts: Record<string, number>
}
export interface PurgeTargetResult {
  status: 'counted' | 'purged'
  target: string
  source: string | null
  counts: Record<string, number>
}

const purgeQuery = (source?: string, dryRun = false) => {
  const q = new URLSearchParams()
  if (source) q.set('source', source)
  if (dryRun) q.set('dry_run', 'true')
  return q.toString() ? `?${q}` : ''
}

export const purgeTargets = (source?: string) =>
  req<{ source: string | null; targets: PurgeTargetRow[] }>(
    `/ingestion/purge-targets${purgeQuery(source)}`,
    {},
    INGESTION_TIMEOUT_MS,
  )
export const purgeTarget = (key: string, opts: { source?: string; dryRun?: boolean } = {}) =>
  req<PurgeTargetResult>(
    `/ingestion/purge/${key}${purgeQuery(opts.source, opts.dryRun)}`,
    { method: 'POST' },
    INGESTION_TIMEOUT_MS,
  )
export const enrich = (kind = 'summary', source?: string) =>
  req<{ status: string; kind: string; source: string | null }>(
    `/ingestion/enrich?kind=${encodeURIComponent(kind)}${source ? `&source=${encodeURIComponent(source)}` : ''}`,
    { method: 'POST' },
    10000,
  )
export const rebuildVectors = () =>
  req<{ status: string }>('/ingestion/rebuild-vectors', { method: 'POST' }, 10000)

export interface SourcePathInfo { source: string; path: string; kind: 'file' | 'dir'; exists: boolean }

export const getSourcePath = (source: string) =>
  req<SourcePathInfo>(`/ingestion/sources/${source}/path`)
export const setSourcePath = (source: string, path: string) =>
  req<SourcePathInfo>(
    `/ingestion/sources/${source}/path`,
    { method: 'PUT', body: JSON.stringify({ path }) },
  )
// Matches PICKER_TIMEOUT_SECONDS in pka/api/source_paths.py, plus slack so the
// backend's own timeout fires first and returns a real error.
const BROWSE_TIMEOUT_MS = 605_000
export const browseSourcePath = (source: string) =>
  req<{ path: string | null }>(`/ingestion/sources/${source}/browse`, { method: 'POST' }, BROWSE_TIMEOUT_MS)

// ── Image folders (the image source is a list of folders) ──────────────────────
export interface ImageDir { path: string; exists: boolean }

export const getImageDirs = () =>
  req<{ dirs: ImageDir[] }>('/ingestion/sources/image/dirs').then(r => r.dirs)
export const addImageDir = (path: string) =>
  req<{ dirs: ImageDir[] }>(
    '/ingestion/sources/image/dirs',
    { method: 'POST', body: JSON.stringify({ path }) },
  ).then(r => r.dirs)
export const removeImageDir = (path: string) =>
  req<{ dirs: ImageDir[] }>(
    '/ingestion/sources/image/dirs',
    { method: 'DELETE', body: JSON.stringify({ path }) },
  ).then(r => r.dirs)
export const browseImageDir = () =>
  req<{ path: string | null }>(
    '/ingestion/sources/image/dirs/browse',
    { method: 'POST' },
    BROWSE_TIMEOUT_MS,
  )

// ── Images ────────────────────────────────────────────────────────────────────

export const listImages   = (params?: { image_type?: string; limit?: number; offset?: number }) => {
  const qs = new URLSearchParams(params as Record<string,string>).toString()
  return req<ImageOut[]>(`/images${qs ? '?' + qs : ''}`)
}
export const searchImages = (q: string, n = 10, mode: 'hybrid' | 'clip' | 'text' = 'hybrid') =>
  req<ImageOut[]>(`/images/search?q=${encodeURIComponent(q)}&n=${n}&mode=${mode}`)
export const getImage     = (id: number) => req<ImageOut>(`/images/${id}`)

// ── Reading lists ─────────────────────────────────────────────────────────────

export const listReadingLists = () => req<ReadingList[]>('/reading-lists')
export const createReadingList = (name: string, description = '') =>
  req<{ list_id: number }>('/reading-lists', { method: 'POST', body: JSON.stringify({ name, description }) })
export const deleteReadingList = (id: number) =>
  req<void>(`/reading-lists/${id}`, { method: 'DELETE' })
export const getListItems  = (id: number) => req<ReadingListItem[]>(`/reading-lists/${id}/items`)
export const addListItem   = (listId: number, document_id: number, note = '') =>
  req<{ id: number }>(`/reading-lists/${listId}/items`, { method: 'POST', body: JSON.stringify({ document_id, note }) })
export const removeListItem = (listId: number, itemId: number) =>
  req<void>(`/reading-lists/${listId}/items/${itemId}`, { method: 'DELETE' })

// ── Tag training (active learning) ───────────────────────────────────────────

export interface TagTrainingLabel { doc_id: number; label: number }
export interface TagTrainingSession {
  session_id: number
  tag: string
  status: string
  created_at: number
  accepted_at: number | null
  parameters: Record<string, unknown>
  provenance: Record<string, unknown> | null
  positive_count: number
  negative_count: number
  has_model: boolean
  train_stats: Record<string, unknown> | null
  bootstrap_negatives_added?: number
  pseudo_label_result?: {
    mode: string
    added_positive: number
    added_negative: number
    pseudo_label_high?: number
    pseudo_label_low?: number
    errors?: number
    batch_size?: number
  }
}
export interface TagTrainingQueueDoc {
  doc_id: number
  title: string
  probability: number
  uncertainty: number
}

export const listTagTrainingSessions = () =>
  req<TagTrainingSession[]>('/tag-training/sessions')
export const getTagTrainingSession = (id: number) =>
  req<TagTrainingSession>(`/tag-training/sessions/${id}`)
export const createTagTrainingSession = (tag: string, labels: TagTrainingLabel[]) =>
  req<TagTrainingSession>('/tag-training/sessions', {
    method: 'POST',
    body: JSON.stringify({ tag, labels }),
  })
// ── Duplicate documents ───────────────────────────────────────────────────────

export const listDuplicates = (state?: 'candidate' | 'merged' | 'rejected') =>
  req<DuplicateLink[]>(`/duplicates${state ? `?state=${state}` : ''}`)
// Compares every document vector for near duplicates: can take a while.
export const scanDuplicates = () =>
  req<DuplicateScanResult>('/duplicates/scan', { method: 'POST', body: '{}' }, 600_000)
export const acceptDuplicate = (id: number) =>
  req<DuplicateLink>(`/duplicates/${id}/accept`, { method: 'POST' })
export const rejectDuplicate = (id: number) =>
  req<void>(`/duplicates/${id}/reject`, { method: 'POST' })

// ── Tag folding ───────────────────────────────────────────────────────────────

export const listTagAliases = (state?: 'candidate' | 'active' | 'rejected') =>
  req<TagAlias[]>(`/tags/aliases${state ? `?state=${state}` : ''}`)
export const mergeTags = (alias: string, canonical: string) =>
  req<TagAlias>('/tags/aliases', { method: 'POST', body: JSON.stringify({ alias, canonical }) })
export const acceptTagAlias = (id: number) =>
  req<TagAlias>(`/tags/aliases/${id}/accept`, { method: 'POST' })
export const rejectTagAlias = (id: number) =>
  req<void>(`/tags/aliases/${id}/reject`, { method: 'POST' })
// Embeds every compared tag locally: minutes on a large vocabulary.
export const scanTagAliases = () =>
  req<TagAliasScanResult>('/tags/aliases/scan', { method: 'POST', body: '{}' }, 600_000)

export const createTagTrainingFromSourceTag = (sourceTag: string, targetTag: string) =>
  req<TagTrainingSession>('/tag-training/sessions/from-source-tag', {
    method: 'POST',
    body: JSON.stringify({ source_tag: sourceTag, target_tag: targetTag }),
  })
export const getTagTrainingQueue = (sessionId: number) =>
  req<TagTrainingQueueDoc[]>(`/tag-training/sessions/${sessionId}/queue`)
export const postTagTrainingLabels = (sessionId: number, labels: TagTrainingLabel[]) =>
  req<TagTrainingSession>(`/tag-training/sessions/${sessionId}/labels`, {
    method: 'POST',
    body: JSON.stringify({ labels }),
  })
export const acceptTagTrainingSession = (sessionId: number) =>
  req<TagTrainingSession>(`/tag-training/sessions/${sessionId}/accept`, { method: 'POST' })
export const resumeTagTrainingSession = (sessionId: number) =>
  req<TagTrainingSession>(`/tag-training/sessions/${sessionId}/resume`, { method: 'POST' })
export const pseudoLabelTagTrainingSession = (
  sessionId: number,
  mode: 'model' | 'llm',
  batchSize?: number,
) =>
  req<TagTrainingSession>(
    `/tag-training/sessions/${sessionId}/pseudo-label`,
    {
      method: 'POST',
      body: JSON.stringify({ mode, batch_size: batchSize ?? null }),
    },
    mode === 'llm' ? pseudoLabelLlmTimeoutMs(batchSize) : DEFAULT_TIMEOUT_MS,
  )
export const getTagTrainingSessionByTag = (tag: string) =>
  req<TagTrainingSession>(`/tag-training/sessions/by-tag/${encodeURIComponent(tag)}`)

// ── Settings ──────────────────────────────────────────────────────────────────


export const getSettings = () => req<SettingsReport>('/settings')
export const probeCapability = (capability: string) =>
  req<ProbeResult>(`/settings/probe/${capability}`, { method: 'POST' })
